# fly.toml app configuration file generated for swiftstitch-v1 on 2023-08-25T20:28:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "swiftstitch-v1"
primary_region = "sjc"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
